name: build-test-windows

on:
  push:
    paths:
      - "**/windows/Dockerfile"
      - ".github/workflows/build-test-windows.yml"

  pull_request:
    paths:
      - "**/windows/Dockerfile"
      - genMatrix.js
      - ".github/workflows/build-test-windows.yml"

jobs:
  build:
    name: build
    runs-on: windows-2019
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix: 
        version: [ 22 ]
        variant: [ "windows" ]

    steps:
      - name: Get short node version
        uses: actions/github-script@v7
        id: short-version
        with:
          result-encoding: string
          script: return "${{ matrix.version }}".split('.')[0]

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build --file ./${{ steps.short-version.outputs.result }}/${{ matrix.variant }}/Dockerfile --tag node:${{ matrix.version }}-${{ matrix.variant }} .

      - name: Test for node version
        run: |
          image_node_version=$(docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} node --print "process.versions.node")
          echo "Expected: \"${{ matrix.version }}\", Got: \"${image_node_version}\""
          [ "${image_node_version}" == "${{ matrix.version }}" ]

      - name: Verify entrypoint runs regular, non-executable files with node
        run: |
          tmp_file=$(mktemp)
          echo 'console.log("success")' > "${tmp_file}"
          output=$(docker run --rm -v "${tmp_file}:/app/index.js" node:${{ matrix.version }}-${{ matrix.variant }} app/index.js)
          [ "${output}" = 'success' ]

      - name: Test for npm
        run: docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} npm --version

      - name: Test for yarn
        run: docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} yarn --version
