name: build-test-windows

on:
  push:
    paths:
      - "**/windows-2019/Dockerfile"
      - "**/windows-2022/Dockerfile"
      - ".github/workflows/build-test-windows.yml"

  pull_request:
    paths:
      - "**/windows-2019/Dockerfile"
      - "**/windows-2022/Dockerfile"
      - ".github/workflows/build-test-windows.yml"

jobs:
  build-windows-2019:
    name: build-windows-2019
    runs-on: windows-2019
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix: 
        version: [ 22.7.0 ]
        variant: [ "windows-2019" ]

    steps:
      - name: Get short node version
        uses: actions/github-script@v7
        id: short-version
        with:
          result-encoding: string
          script: return "${{ matrix.version }}".split('.')[0]

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build --file ./${{ steps.short-version.outputs.result }}/${{ matrix.variant }}/Dockerfile --tag node:${{ matrix.version }}-${{ matrix.variant }} .

      - name: Test for node version
        shell: pwsh
        run: |
          $image_node_version = (docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} node --print "process.versions.node").Trim() 
          Write-Host "Expected: '${{ matrix.version }}', Got: '$image_node_version'"
          if ($image_node_version -ne ${{ matrix.version }}) {
            exit 1 
          }
        
      - name: Verify entrypoint runs regular, non-executable files with node
        shell: pwsh
        run: |
          $tmp_file = New-TemporaryFile
          "console.log('success')" | Out-File -FilePath $tmp_file -Encoding utf8
          $output = (docker run --rm -v "${{ github.workspace }}\$tmp_file:/app/index.js" node:${{ matrix.version }}-${{ matrix.variant }} app/index.js)
          if ($output -ne 'success') {
            exit 1
          }
        
      - name: Test for npm
        run: docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} npm --version
        
      - name: Test for yarn
        run: docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} yarn --version

  build-windows-2022:
    name: build-windows-2022
    runs-on: windows-2022
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix: 
        version: [ "22.7.0" ]
        variant: [ "windows-2022" ]

    steps:
      - name: Get short node version
        uses: actions/github-script@v7
        id: short-version
        with:
          result-encoding: string
          script: return "${{ matrix.version }}".split('.')[0]

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build --file ./${{ steps.short-version.outputs.result }}/${{ matrix.variant }}/Dockerfile --tag node:${{ matrix.version }}-${{ matrix.variant }} .

      - name: Test for node version
        shell: pwsh
        run: |
          $image_node_version = (docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} node --print "process.versions.node").Trim() 
          Write-Host "Expected: '${{ matrix.version }}', Got: '$image_node_version'"
          $bytes = [System.Text.Encoding]::UTF8.GetBytes("${{ matrix.version }}")
          Write-Host "Matrix version bytes: $bytes"
          $bytes = [System.Text.Encoding]::UTF8.GetBytes($image_node_version)
          Write-Host "Image version bytes: $bytes"
          if ($image_node_version -ne "${{ matrix.version }}") {
            exit 1
          }
        
      - name: Verify entrypoint runs regular, non-executable files with node
        shell: pwsh
        run: |
          $tmp_file = New-TemporaryFile
          "console.log('success')" | Out-File -FilePath $tmp_file -Encoding utf8
          $output = (docker run --rm -v "${{ github.workspace }}\$tmp_file:/app/index.js" node:${{ matrix.version }}-${{ matrix.variant }} app/index.js)
          if ($output -ne 'success') {
            exit 1
          }
        
      - name: Test for npm
        run: docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} npm --version
        
      - name: Test for yarn
        run: docker run --rm node:${{ matrix.version }}-${{ matrix.variant }} yarn --version
